const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const storage=new Map(),sandbox={URL,URLSearchParams,Date,sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},document:{addEventListener(){},referrer:'https://www.tiktok.com/@creator?private=discard',cookie:''},location:{origin:'https://www.mingeagle.com',pathname:'/for-coaches.html',search:'?utm_source=tiktok&utm_medium=organic&utm_campaign=coach-demo'},module:{exports:{}},globalThis:null};sandbox.globalThis=sandbox;
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('public/site.js','utf8'),sandbox);sandbox.location.pathname='/inquiry.html';sandbox.location.search='?type=sample&customer=coach';vm.runInContext(fs.readFileSync('public/forms-core.js','utf8'),sandbox);
const core=sandbox.module.exports,ctx=core.context('Inquiry');assert.equal(ctx.landingPage,'https://www.mingeagle.com/for-coaches.html');assert.ok(ctx.campaign.includes('utm_source=tiktok'));assert.equal(ctx.referrer,'https://www.tiktok.com/@creator');
const config={fields:{reference:'ref',requestType:'type',products:'products',customerType:'customer',quantity:'qty',details:'details',privacy:'privacy'}};const payload=core.buildPayload({reference:'fixture',firstname:'Fixture',email:'fixture@example.test',requestType:'Sample request'},config,ctx);const details=payload.fields.find(x=>x.name==='details').value;assert.ok(details.includes('utm_campaign=coach-demo'));assert.ok(details.includes('Landing page: https://www.mingeagle.com/for-coaches.html'));assert.ok(!details.includes('private=discard'));
sandbox.location.search='?utm_source=partner&utm_campaign=academy';vm.runInContext(fs.readFileSync('public/site.js','utf8').slice(fs.readFileSync('public/site.js','utf8').indexOf('(function captureInquirySource')),sandbox);assert.ok(core.context('Inquiry').campaign.includes('utm_source=partner'));
const languages=JSON.parse(fs.readFileSync('public/i18n.json','utf8'));for(const [lang,dict]of Object.entries(languages))for(let i=0;i<22;i++)assert.ok(dict['growth.'+i],lang+' missing growth.'+i);
const html=fs.readFileSync('public/for-coaches.html','utf8');assert.ok(html.includes('rel="canonical"'));assert.ok(html.includes('customer=coach'));assert.ok(fs.readFileSync('public/sitemap.xml','utf8').includes('/for-coaches.html'));
for(const source of ['facebook','instagram','youtube','tiktok']){sandbox.location.search='?utm_source='+source+'&utm_campaign=us_quiet_play_202610';vm.runInContext(fs.readFileSync('public/site.js','utf8').slice(fs.readFileSync('public/site.js','utf8').indexOf('(function captureInquirySource')),sandbox);const c=core.context('Inquiry');assert.ok(c.campaign.includes('utm_source='+source));assert.ok(c.campaign.includes('utm_campaign=us_quiet_play_202610'));}
console.log('PASS: campaign survives navigation, referrer query discarded, inquiry metadata includes landing/source, later campaign updates and all nine languages complete.');
