from pathlib import Path
import re
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else 'public')
overrides = Path(__file__).resolve().parent

# Append V20 styles once.
css_path = root / 'styles.css'
css = css_path.read_text(encoding='utf-8')
extra = (overrides / 'v20_polish.css').read_text(encoding='utf-8')
if 'MING EAGLE V20' not in css:
    css_path.write_text(css + '\n\n' + extra + '\n', encoding='utf-8')


def replace_gallery(page_name: str, snippet: str) -> None:
    path = root / page_name
    text = path.read_text(encoding='utf-8')
    pattern = re.compile(
        r'<section class="section"><div class="wrap"><div class="eyebrow" data-i18n="common\.gallery">REAL PRODUCT HIGHLIGHTS</div>.*?</section>',
        re.S,
    )
    if 'id="real-product-highlights"' in text:
        return
    match = pattern.search(text)
    if not match:
        raise SystemExit(f'V20 highlight section not found in {page_name}')
    text = text[:match.start()] + snippet + text[match.end():]
    path.write_text(text, encoding='utf-8')


p1 = r'''<section class="section realHighlightsV20" id="real-product-highlights"><div class="wrap"><div class="eyebrow">REAL PRODUCT HIGHLIGHTS</div><h2>QUIETER INDOOR PLAY, BUILT AS A COMPLETE SET.</h2><p class="lead highlightLead">The flocked silent basketball set combines the soft PU ball customers want with a compact adhesive hoop, making the value easy to understand at a glance.</p><div class="highlightMosaic"><article class="highlightHeroCard"><img src="assets/silent-set.jpg" alt="Flocked Silent Basketball Set with mini hoop"/><div class="highlightHeroOverlay"><span class="micro">THE COMPLETE SET</span><h3>Ball + hoop. Ready for home play.</h3><p>A soft flocked silent basketball paired with the orange mini hoop for bedrooms, playrooms, apartments and family shooting games.</p></div></article><article class="highlightPointCard orange"><div class="bigStat">3 <small>SIZES</small></div><div><h3>No. 3 / 5 / 7</h3><p>Choose a size for younger players, family use or older users without changing the core play experience.</p></div></article><article class="highlightPointCard blue"><div class="bigStat">0 <small>PUMP</small></div><div><h3>Non-inflatable PU foam</h3><p>No air pump required. The foam body compresses on impact to soften the sharp floor slap of a conventional ball.</p></div></article><article class="highlightPointCard gold"><div class="bigStat">30 <small>CM</small></div><div><h3>Compact adhesive hoop</h3><p>Approx. 11.8 in hoop diameter. Designed for smooth, clean and stable indoor mounting surfaces.</p></div></article><article class="highlightPointCard mint"><div class="bigStat">2 <small>COLORS</small></div><div><h3>Orange / Blue</h3><p>Simple, recognizable color options for retail, samples and wholesale programs.</p></div></article></div><div class="highlightProofBar"><div class="highlightProof"><b>Soft flocked touch</b><span>More comfortable for indoor handling.</span></div><div class="highlightProof"><b>Quieter impact</b><span>Foam construction helps reduce sharp contact noise.</span></div><div class="highlightProof"><b>Indoor focused</b><span>Best on clean indoor floors and controlled play areas.</span></div><div class="highlightProof"><b>Use guide included</b><span>Installation, recovery, cleaning and safety instructions.</span></div></div><div class="highlightCta"><div><b>Want the installation and care details?</b><p>See the complete silent basketball guide before first use.</p></div><a class="btn orange" href="silent-basketball-guide.html#instructions">Open use &amp; care guide</a></div></div></section>'''

p2 = r'''<section class="section realHighlightsV20" id="real-product-highlights"><div class="wrap"><div class="eyebrow">REAL PRODUCT HIGHLIGHTS</div><h2>A SOFTER COVERED FEEL FOR EVERYDAY HOME PLAY.</h2><p class="lead highlightLead">The fabric-cover model adds a textile-style outer touch to the same non-inflatable silent-ball idea, giving buyers a visibly different surface option.</p><div class="highlightMosaic"><article class="highlightHeroCard"><img src="assets/fabric-ball.jpg" alt="Fabric-Cover Silent Basketball Set"/><div class="highlightHeroOverlay"><span class="micro">SOFT-TOUCH OPTION</span><h3>Fabric-cover feel. Silent-ball core.</h3><p>A covered surface for customers who prefer a more finished touch while keeping the no-pump, indoor-play format.</p></div></article><article class="highlightPointCard sky"><div class="bigStat">3 <small>SIZES</small></div><div><h3>No. 3 / 5 / 7</h3><p>A straightforward size range for family, youth and general indoor play.</p></div></article><article class="highlightPointCard mint"><div class="bigStat">2 <small>COLORS</small></div><div><h3>Orange / Green</h3><p>Two clear assortment directions for samples, retail displays and wholesale selection.</p></div></article><article class="highlightPointCard ink"><div class="bigStat">PU <small>CORE</small></div><div><h3>Non-inflatable structure</h3><p>The foam body needs no pump and is designed to produce a softer indoor impact sound.</p></div></article><article class="highlightPointCard gold"><div class="bigStat">SET <small>READY</small></div><div><h3>Mini hoop compatible</h3><p>Available as a home-play set with the same compact adhesive hoop format.</p></div></article></div><div class="highlightProofBar"><div class="highlightProof"><b>Fabric-cover surface</b><span>A distinct hand feel versus bare foam.</span></div><div class="highlightProof"><b>Family-friendly use</b><span>Built for light indoor games and interaction.</span></div><div class="highlightProof"><b>No inflation</b><span>Simple setup after unpacking and recovery.</span></div><div class="highlightProof"><b>Private-label ready</b><span>Customization reviewed by quantity and artwork.</span></div></div></div></section>'''

p3 = r'''<section class="section realHighlightsV20" id="real-product-highlights"><div class="wrap"><div class="eyebrow">REAL PRODUCT HIGHLIGHTS</div><h2>TRAINING FEEL WITHOUT THE HARD INDOOR IMPACT.</h2><p class="lead highlightLead">This weighted flocked model is the training-first choice in the range, with more substantial hand feel and deeper basketball-style grip channels.</p><div class="highlightMosaic"><article class="highlightHeroCard"><img src="assets/flocked-ball.jpg" alt="Weighted Flocked Silent Basketball"/><div class="highlightHeroOverlay"><span class="micro">TRAINING-FIRST</span><h3>More resistance. More deliberate control.</h3><p>A weighted PU foam basketball for handling drills, coordination work and quieter indoor practice.</p></div></article><article class="highlightPointCard orange"><div class="bigStat">+ <small>WEIGHT</small></div><div><h3>Weighted construction</h3><p>A more substantial feel than lightweight family-play silent balls. Exact weight is confirmed by size before ordering.</p></div></article><article class="highlightPointCard ink"><div class="bigStat">DEEP <small>GRIP</small></div><div><h3>Pronounced channels</h3><p>Deeper basketball-style channels support hand placement and control during drills.</p></div></article><article class="highlightPointCard mint"><div class="bigStat">3 <small>SIZES</small></div><div><h3>No. 3 / 5 / 7</h3><p>Current website assortment covers compact practice through full-size handling formats.</p></div></article><article class="highlightPointCard sky"><div class="bigStat">3 <small>COLORS</small></div><div><h3>Orange / Brown / Black</h3><p>Training-oriented color choices with a soft flocked exterior.</p></div></article></div><div class="highlightProofBar"><div class="highlightProof"><b>Weighted feel</b><span>Designed for deliberate training use.</span></div><div class="highlightProof"><b>Flocked surface</b><span>Soft touch with added friction.</span></div><div class="highlightProof"><b>No pump</b><span>PU foam structure is non-inflatable.</span></div><div class="highlightProof"><b>Indoor drills</b><span>Best for controlled handling and coordination work.</span></div></div></div></section>'''

p4 = r'''<section class="section realHighlightsV20" id="real-product-highlights"><div class="wrap"><div class="eyebrow">REAL PRODUCT HIGHLIGHTS</div><h2>INDOOR FOOTWORK WITH A SOFTER, QUIETER TOUCH.</h2><p class="lead highlightLead">The flocked silent soccer ball brings the same foamed-PU concept to a familiar size-5 football format for kids, teens and family play indoors.</p><div class="highlightMosaic"><article class="highlightHeroCard"><img src="assets/flocked-soccer.jpg" alt="Flocked Silent Soccer Ball"/><div class="highlightHeroOverlay"><span class="micro">INDOOR FOOTBALL</span><h3>Size-5 proportions for small-space play.</h3><p>A soft flocked soccer ball designed for controlled footwork, passing games and home entertainment.</p></div></article><article class="highlightPointCard blue"><div class="bigStat">5 <small>SIZE</small></div><div><h3>Approx. 21.5 cm</h3><p>Familiar soccer-ball proportions in a softer indoor-focused construction.</p></div></article><article class="highlightPointCard orange"><div class="bigStat">4 <small>COLORS</small></div><div><h3>Four colorways</h3><p>Black/White, Black/Green, Black/Orange and Black/Gold.</p></div></article><article class="highlightPointCard mint"><div class="bigStat">PU <small>FOAM</small></div><div><h3>Soft flocked surface</h3><p>Foamed PU construction creates a softer touch than a conventional hard synthetic football.</p></div></article><article class="highlightPointCard gold"><div class="bigStat">HOME <small>PLAY</small></div><div><h3>Kids &amp; teen focused</h3><p>Designed for indoor entertainment, basic footwork and parent-child play rather than hard outdoor match use.</p></div></article></div><div class="highlightProofBar"><div class="highlightProof"><b>Indoor footwork</b><span>Controlled passing and touch practice.</span></div><div class="highlightProof"><b>Soft-contact feel</b><span>Flocked foam construction for home use.</span></div><div class="highlightProof"><b>Four colorways</b><span>Easy retail assortment planning.</span></div><div class="highlightProof"><b>Size 5 format</b><span>Familiar proportions for older kids and teens.</span></div></div></div></section>'''

replace_gallery('silent-basketball.html', p1)
replace_gallery('fabric-silent-basketball.html', p2)
replace_gallery('weighted-flocked-basketball.html', p3)
replace_gallery('silent-soccer.html', p4)

# Curate the first product's creator videos: wider cards and only three live embeds.
p = root / 'silent-basketball.html'
text = p.read_text(encoding='utf-8')
if 'productVideoRail' not in text:
    text = text.replace('class="creatorRail productRail"', 'class="creatorRail productRail productVideoRail"', 1)
    note = '<div class="productVideoNote"><span><b>3 featured creator videos</b> · Wider players for reliable loading on the product page.</span><a href="videos.html#flocked-silent-basketball">See all 16 creator clips →</a></div>'
    text = text.replace('<div class="creatorRailShell">', note + '<div class="creatorRailShell">', 1)
    limiter = r'''<script>(function(){var cards=document.querySelectorAll('.creatorProduct .productVideoRail .creatorVideoCard');cards.forEach(function(card,i){if(i>=3)card.remove();});})();</script>'''
    text = text.replace('</body>', limiter + '</body>')
p.write_text(text, encoding='utf-8')

print('V20 polish applied: four visual highlight sections + curated product TikTok strip.')
