interface Env { MINGEAGLE_DB: D1Database }

type Input = { stateCode?: string; customerType?: string; targetCount?: number | string };
type Hit = { title:string; url:string; snippet:string; query:string; city:string };
type Verified = Hit & { name:string; website:string; email:string; phone:string; contactName:string; contactTitle:string; contactUrl:string; facebook:string; instagram:string; linkedin:string; score:number; evidence:string; sourceUrls:string[] };

const clean=(v:unknown,max=1000)=>typeof v==='string'?v.trim().replace(/\s+/g,' ').slice(0,max):'';
const allowedState=/^[A-Z]{2}$/;
const allowedTypes=new Set(['BASKETBALL_TRAINING','BASKETBALL_GYM','YOUTH_CLUB','SPORTS_STORE']);

const STATE_NAMES:Record<string,string>={AL:'Alabama',AK:'Alaska',AZ:'Arizona',AR:'Arkansas',CA:'California',CO:'Colorado',CT:'Connecticut',DE:'Delaware',FL:'Florida',GA:'Georgia',HI:'Hawaii',ID:'Idaho',IL:'Illinois',IN:'Indiana',IA:'Iowa',KS:'Kansas',KY:'Kentucky',LA:'Louisiana',ME:'Maine',MD:'Maryland',MA:'Massachusetts',MI:'Michigan',MN:'Minnesota',MS:'Mississippi',MO:'Missouri',MT:'Montana',NE:'Nebraska',NV:'Nevada',NH:'New Hampshire',NJ:'New Jersey',NM:'New Mexico',NY:'New York',NC:'North Carolina',ND:'North Dakota',OH:'Ohio',OK:'Oklahoma',OR:'Oregon',PA:'Pennsylvania',RI:'Rhode Island',SC:'South Carolina',SD:'South Dakota',TN:'Tennessee',TX:'Texas',UT:'Utah',VT:'Vermont',VA:'Virginia',WA:'Washington',WV:'West Virginia',WI:'Wisconsin',WY:'Wyoming'};
const METROS:Record<string,string[]>={
TX:['Dallas','Houston','Austin','San Antonio','Fort Worth','Plano','Frisco','Arlington'],CA:['Los Angeles','San Diego','San Francisco','Sacramento','Irvine','Anaheim'],FL:['Miami','Orlando','Tampa','Jacksonville','Fort Lauderdale'],NY:['New York City','Buffalo','Rochester','Albany'],PA:['Philadelphia','Pittsburgh','Harrisburg'],OH:['Columbus','Cleveland','Cincinnati'],IL:['Chicago','Aurora','Naperville'],GA:['Atlanta','Savannah','Augusta'],NC:['Charlotte','Raleigh','Greensboro'],VA:['Richmond','Virginia Beach','Alexandria'],WA:['Seattle','Tacoma','Spokane'],AZ:['Phoenix','Tucson','Mesa'],CO:['Denver','Colorado Springs','Aurora'],TN:['Nashville','Memphis','Knoxville'],MA:['Boston','Worcester','Springfield'],MI:['Detroit','Grand Rapids','Ann Arbor'],NJ:['Newark','Jersey City','Trenton'],MD:['Baltimore','Silver Spring','Rockville'],IN:['Indianapolis','Fort Wayne'],MO:['St Louis','Kansas City'],WI:['Milwaukee','Madison'],MN:['Minneapolis','Saint Paul'],OR:['Portland','Eugene'],KY:['Louisville','Lexington'],SC:['Columbia','Charleston','Greenville'],LA:['New Orleans','Baton Rouge'],OK:['Oklahoma City','Tulsa'],UT:['Salt Lake City','Provo'],NV:['Las Vegas','Reno']
};
const FALLBACK=['largest city','capital'];
const TERMS:Record<string,string[]>={
BASKETBALL_TRAINING:['"private basketball lessons"','"basketball camp" academy','"basketball coach" training','"hoops academy"','"basketball clinic" training','"basketball player development"'],
BASKETBALL_GYM:['"basketball training facility"','"indoor basketball gym"','"basketball court rental"','"basketball sports center"','"open gym basketball"'],
YOUTH_CLUB:['"AAU basketball club"','"youth basketball tryouts"','"youth hoops club"','"basketball travel team"','"youth basketball academy"'],
SPORTS_STORE:['"basketball equipment store"','"basketball sporting goods"','"basketball gear shop"','"basketball retail store"','"basketball shoes store"']
};
const BLOCKED=['bing.com','google.com','duckduckgo.com','yahoo.com','yelp.com','facebook.com','instagram.com','linkedin.com','youtube.com','wikipedia.org','reddit.com','x.com','twitter.com','tiktok.com','pinterest.com','yellowpages.com','mapquest.com','tripadvisor.com','indeed.com','ziprecruiter.com','chamberofcommerce.com','manta.com','bbb.org','eventbrite.com','foursquare.com','nba.com','wnba.com','espn.com','cbssports.com','foxsports.com','basketball-reference.com','maxpreps.com','hudl.com','flashscore.com','livescore.com','sofascore.com','scores24.live','365scores.com','sports-reference.com','stathead.com','teamrankings.com','realgm.com','rotowire.com','bleacherreport.com','sports.yahoo.com','si.com','usatoday.com','theathletic.com','sportskeeda.com','crazygames.com','poki.com','games.com','miniclip.com','formula1.com'];
const HARD_NEG=/\b(formula\s*1|motorsport|racing|live\s*score|livescore|box\s*score|betting|odds|video game|online game|play game|fantasy basketball|sportsbook|breaking news|player stats?|team stats?|standings|scoreboard)\b/i;
const GENERIC=/^(home|basketball|adult basketball|youth basketball|basketball training|basketball academy|basketball program|training|academy|programs?|sports|athletics|contact|about|team|coaches?|schedule|calendar|news|scores|standings|shop|store)$/i;
const SERVICE=/\b(register|registration|enroll|book now|schedule|private lesson|training session|membership|pricing|tuition|tryouts?|programs?|services?|camp|clinic|shop|store|add to cart|buy now|contact us|facility rental|court rental)\b/i;
const NEG_PUBLISHER=/\b(latest news|breaking news|articles?|editorial|journalist|box scores|standings|statistics|player database|game recap|match preview|odds|betting picks?)\b/i;
const TYPE_MATCH:Record<string,RegExp>={
BASKETBALL_TRAINING:/(?:basketball|hoops).{0,140}(?:academy|training|skills?|coaching|player development|private lessons?|camp|clinic|sessions?)|(?:academy|training|skills?|coaching|player development|private lessons?|camp|clinic|sessions?).{0,140}(?:basketball|hoops)/i,
BASKETBALL_GYM:/(?:basketball|hoops).{0,140}(?:gym|facility|sports? cent(?:er|re)|court rental|open gym|indoor court)|(?:gym|facility|sports? cent(?:er|re)|court rental|open gym|indoor court).{0,140}(?:basketball|hoops)/i,
YOUTH_CLUB:/(?:basketball|hoops).{0,140}(?:youth|aau|club|tryouts?|travel team|league)|(?:youth|aau|club|tryouts?|travel team|league).{0,140}(?:basketball|hoops)/i,
SPORTS_STORE:/(?:basketball|hoops).{0,140}(?:sporting goods|store|shop|equipment|retail|gear|balls?|shoes?)|(?:sporting goods|store|shop|equipment|retail|gear).{0,140}(?:basketball|hoops)/i
};

function decode(v:string){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&apos;|&#39;|&#x27;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
function strip(v:string){return decode(v.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim())}
function xml(block:string,tag:string){const m=block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?strip(m[1]):''}
function domainOf(v:string){try{return new URL(v).hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
function allowedUrl(v:string){try{const u=new URL(v);const h=domainOf(v);return /^https?:$/.test(u.protocol)&&!!h&&!BLOCKED.some(d=>h===d||h.endsWith(`.${d}`))}catch{return false}}
function validEmail(v:string){const e=v.toLowerCase().replace(/^mailto:/,'').split('?')[0].trim();if(!/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9.-]+\.[a-z]{2,}$/i.test(e))return '';if(/\.(png|jpg|jpeg|gif|webp|svg|css|js)$/i.test(e)||/^(example|test|name)@/i.test(e))return '';return e.slice(0,320)}
function grade(score:number){return score>=80?'A':score>=60?'B':'C'}
function normalizeName(v:string){return clean(v,120).replace(/^(welcome to|official website of)\s+/i,'').replace(/\s+(official site|official website|home page)$/i,'').replace(/[|–—:-]+$/,'').trim()}
function genericName(v:string){const n=normalizeName(v);return !n||n.length<3||n.length>100||GENERIC.test(n)||HARD_NEG.test(n)}
function rootUrl(v:string){try{return new URL(v).origin+'/'}catch{return v}}

async function fetchText(url:string,timeout=5200){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{accept:'text/html,application/xhtml+xml,application/rss+xml,application/xml;q=0.9,*/*;q=0.8','accept-language':'en-US,en;q=0.9','user-agent':'Mozilla/5.0 (compatible; MING-EAGLE-Discovery-Expansion/1.0; +https://mingeagle.com)'},redirect:'follow',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return (await r.text()).slice(0,520000)}finally{clearTimeout(t)}}
function meta(html:string,key:string){const e=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const p of [new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,'i')]){const m=html.match(p);if(m)return strip(m[1])}return ''}
function titleOf(html:string){const m=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?strip(m[1]):''}
function hrefs(html:string,base:string){const out:string[]=[];for(const m of html.matchAll(/href\s*=\s*["']([^"']+)["']/gi)){const raw=decode(m[1]).trim();if(!raw||raw.startsWith('#')||/^(javascript|data):/i.test(raw))continue;try{out.push(new URL(raw,base).toString())}catch{}}return [...new Set(out)]}
function emails(html:string){const out=new Set<string>();for(const m of decode(html).matchAll(/mailto:([^"'<>\s?]+)/gi)){const e=validEmail(m[1]);if(e)out.add(e)}for(const raw of decode(html).match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]){const e=validEmail(raw);if(e)out.add(e)}return [...out]}
function phone(text:string){return (text.match(/(?:\+?1[\s.\-()]*)?(?:\(?\d{3}\)?[\s.\-]*)\d{3}[\s.\-]*\d{4}(?:\s*(?:x|ext\.?)\s*\d{1,6})?/gi)||[])[0]||''}
function social(links:string[],domain:string){return links.find(x=>{try{const h=new URL(x).hostname.toLowerCase();return h===domain||h.endsWith(`.${domain}`)}catch{return false}})||''}

function jsonLdNames(html:string){const out:string[]=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m:RegExpExecArray|null;function walk(v:unknown){if(Array.isArray(v)){for(const x of v)walk(x);return}if(!v||typeof v!=='object')return;const o=v as Record<string,unknown>;const t=o['@type'];const types=Array.isArray(t)?t.map(String):[String(t||'')];if(types.some(x=>/Organization|LocalBusiness|SportsOrganization|SportsActivityLocation|ExerciseGym|HealthClub|Store|SportingGoodsStore|EducationalOrganization|Corporation/i.test(x))){if(typeof o.name==='string')out.push(o.name);if(typeof o.legalName==='string')out.push(o.legalName)}for(const [k,x] of Object.entries(o)){if(['@graph','publisher','provider','parentOrganization','brand','department'].includes(k))walk(x)}}while((m=re.exec(html))){try{walk(JSON.parse(decode(m[1]).trim()))}catch{}}return out}
function entityName(html:string,hit:Hit){const candidates:string[]=[...jsonLdNames(html),meta(html,'og:site_name'),meta(html,'application-name')];for(const t of [titleOf(html),hit.title]){for(const p of t.split(/\s+[|–—:]\s+|\s+-\s+/))candidates.push(p)}const d=domainOf(hit.url);candidates.push(d.split('.')[0].replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()));for(const c of candidates){const n=normalizeName(c);if(!genericName(n))return n}return ''}
function extractPerson(text:string){const roles='Owner|Founder|Co-Founder|Executive Director|Program Director|Basketball Director|Training Director|Head Coach|General Manager|Operations Director|Purchasing Manager|Procurement Manager|Athletic Director|Director|Coach|Manager|President|CEO';const name="([A-Z][A-Za-z'’-]{1,30}(?:\\s+[A-Z][A-Za-z'’-]{1,30}){1,2})";for(const [i,p] of [new RegExp(`${name}\\s*(?:[-–—|,:]|\\bis\\s+(?:the\\s+)?)\\s*(${roles})`),new RegExp(`(${roles})\\s*(?:[-–—|,:])?\\s*${name}`)].entries()){const m=text.match(p);if(!m)continue;const person=i===0?m[1]:m[2],title=i===0?m[2]:m[1];if(!/\b(the|our|your|basketball|academy|training|program|team|contact|about|director|coach|manager|staff|sports|adult|youth)\b/i.test(person))return {name:clean(person,120),title:clean(title,120)}}return {name:'',title:''}}

async function bing(q:string,city:string){const query=`${q} ${city} -Formula1 -racing -livescore -stats -standings -betting -games -news`;const data=await fetchText(`https://www.bing.com/search?q=${encodeURIComponent(query)}&format=rss&count=20&mkt=en-US&setlang=en-US`,6500);const items=data.match(/<item\b[\s\S]*?<\/item>/gi)||[];const out:Hit[]=[];const seen=new Set<string>();for(const item of items){const title=xml(item,'title'),url=decode(xml(item,'link')),snippet=xml(item,'description'),d=domainOf(url);if(!title||!url||!d||seen.has(d)||!allowedUrl(url)||HARD_NEG.test(`${title} ${snippet}`))continue;seen.add(d);out.push({title,url,snippet,query,city});if(out.length>=15)break}return out}
function preScore(h:Hit,type:string){const s=`${h.title} ${h.snippet}`;let n=0;if(TYPE_MATCH[type]?.test(s))n+=15;if(/academy|training|skills|coach|lessons?|camp|clinic|player development|aau|youth|gym|facility|sporting goods|store|shop/i.test(s))n+=8;if(SERVICE.test(s))n+=5;if(new RegExp(`\\b${h.city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(s))n+=3;return n}

async function verify(hit:Hit,type:string,stateCode:string):Promise<Verified|null>{try{const root=rootUrl(hit.url);const urls=[root];if(hit.url!==root)urls.push(hit.url);const pages:string[]=[];for(const u of urls){try{pages.push(await fetchText(u,4800))}catch{pages.push('')}}const home=pages[0]||pages[1]||'';if(!home)return null;const name=entityName(home,hit);if(!name)return null;const internal=hrefs(home,root).filter(x=>{try{return new URL(x).origin===new URL(root).origin&&/(contact|about|program|training|coach|team|staff|camp|clinic|lesson|leadership|director)/i.test(new URL(x).pathname)}catch{return false}});if(internal[0]){try{urls.push(internal[0]);pages.push(await fetchText(internal[0],3800))}catch{}}
  const html=pages.join('\n'),text=pages.map(strip).join(' ').slice(0,260000),search=`${hit.title} ${hit.snippet}`,all=`${search} ${text}`;if(HARD_NEG.test(search)||!TYPE_MATCH[type]?.test(all))return null;const neg=(all.match(new RegExp(NEG_PUBLISHER.source,'gi'))||[]).length,pos=(all.match(new RegExp(SERVICE.source,'gi'))||[]).length;if(neg>=4&&pos===0)return null;const state=STATE_NAMES[stateCode]||stateCode;const local=new RegExp(`\\b(${hit.city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}|${state.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})\\b`,'i').test(all);if(!local)return null;
  const links=pages.flatMap((p,i)=>hrefs(p,urls[i]||root));const em=emails(html);const domain=domainOf(root);const email=em.find(e=>e.endsWith(`@${domain}`))||em.find(e=>/^(sales|info|contact|hello|office|admin|coach|training|director)@/i.test(e))||em[0]||'';const ph=phone(text);const person=extractPerson(text);let score=72;if(TYPE_MATCH[type].test(search))score+=6;if(SERVICE.test(all))score+=6;if(email)score+=5;if(ph)score+=3;if(person.name)score+=3;score=Math.min(96,score);
  return {...hit,name,website:root,email,phone:ph,contactName:person.name,contactTitle:person.title,contactUrl:internal.find(x=>/contact/i.test(x))||internal[0]||root,facebook:social(links,'facebook.com'),instagram:social(links,'instagram.com'),linkedin:social(links,'linkedin.com'),score,evidence:`Web expansion V1 · diversified local search · business+location verified · query=${hit.query}`.slice(0,1000),sourceUrls:[...new Set(urls)].slice(0,3)}
}catch{return null}}

async function ensureTables(db:D1Database){await db.prepare(`CREATE TABLE IF NOT EXISTS discovery_jobs (id TEXT PRIMARY KEY,country TEXT NOT NULL DEFAULT 'US',state_region TEXT NOT NULL,customer_type TEXT NOT NULL,target_count INTEGER NOT NULL DEFAULT 20,source_provider TEXT NOT NULL DEFAULT 'OPENSTREETMAP',status TEXT NOT NULL DEFAULT 'RUNNING',result_count INTEGER NOT NULL DEFAULT 0,error TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TEXT)`).run();await db.prepare(`CREATE TABLE IF NOT EXISTS discovery_candidates (id TEXT PRIMARY KEY,source_key TEXT NOT NULL UNIQUE,source_provider TEXT NOT NULL DEFAULT 'OPENSTREETMAP',name TEXT NOT NULL,customer_type TEXT NOT NULL,country TEXT NOT NULL DEFAULT 'US',state_region TEXT,city TEXT,address TEXT,website TEXT,email TEXT,phone TEXT,whatsapp TEXT,instagram_url TEXT,facebook_url TEXT,latitude REAL,longitude REAL,lead_score INTEGER NOT NULL DEFAULT 0,grade TEXT NOT NULL DEFAULT 'C',status TEXT NOT NULL DEFAULT 'NEW',source_url TEXT NOT NULL,source_evidence TEXT,raw_json TEXT,crm_lead_id TEXT,discovered_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();const info=await db.prepare(`PRAGMA table_info(discovery_candidates)`).all<{name:string}>();const names=new Set(info.results.map(r=>r.name));for(const [n,d] of [['linkedin_url','TEXT'],['contact_person_name','TEXT'],['contact_person_title','TEXT'],['website_contact_url','TEXT'],['enrichment_status',`TEXT NOT NULL DEFAULT 'NOT_STARTED'`],['enrichment_source_urls','TEXT'],['enrichment_error','TEXT'],['enriched_at','TEXT']] as Array<[string,string]>){if(!names.has(n)){try{await db.prepare(`ALTER TABLE discovery_candidates ADD COLUMN ${n} ${d}`).run()}catch{}}}}

async function save(db:D1Database,hits:Verified[],state:string,type:string,target:number){let saved=0;const seen=new Set<string>();for(const h of hits.sort((a,b)=>b.score-a.score)){if(saved>=target)break;const domain=domainOf(h.website);if(!domain||seen.has(domain))continue;seen.add(domain);await db.prepare(`INSERT INTO discovery_candidates (id,source_key,source_provider,name,customer_type,state_region,city,website,email,phone,instagram_url,facebook_url,linkedin_url,contact_person_name,contact_person_title,website_contact_url,lead_score,grade,status,source_url,source_evidence,raw_json,enrichment_status,enrichment_source_urls,enriched_at) VALUES (?,?,'WEB_EXPANSION_V1',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, 'NEW',?,?,?,'COMPLETED',?,CURRENT_TIMESTAMP) ON CONFLICT(source_key) DO UPDATE SET source_provider=CASE WHEN discovery_candidates.source_provider='WEB_SEARCH_VERIFIED_V6' THEN discovery_candidates.source_provider ELSE 'WEB_EXPANSION_V1' END,name=CASE WHEN discovery_candidates.source_provider='WEB_SEARCH_VERIFIED_V6' THEN discovery_candidates.name ELSE excluded.name END,customer_type=excluded.customer_type,state_region=excluded.state_region,city=COALESCE(discovery_candidates.city,excluded.city),website=COALESCE(discovery_candidates.website,excluded.website),email=COALESCE(discovery_candidates.email,excluded.email),phone=COALESCE(discovery_candidates.phone,excluded.phone),instagram_url=COALESCE(discovery_candidates.instagram_url,excluded.instagram_url),facebook_url=COALESCE(discovery_candidates.facebook_url,excluded.facebook_url),linkedin_url=COALESCE(discovery_candidates.linkedin_url,excluded.linkedin_url),contact_person_name=COALESCE(discovery_candidates.contact_person_name,excluded.contact_person_name),contact_person_title=COALESCE(discovery_candidates.contact_person_title,excluded.contact_person_title),website_contact_url=COALESCE(discovery_candidates.website_contact_url,excluded.website_contact_url),lead_score=MAX(discovery_candidates.lead_score,excluded.lead_score),grade=CASE WHEN MAX(discovery_candidates.lead_score,excluded.lead_score)>=80 THEN 'A' WHEN MAX(discovery_candidates.lead_score,excluded.lead_score)>=60 THEN 'B' ELSE 'C' END,status=CASE WHEN discovery_candidates.status='CRM' THEN 'CRM' ELSE 'NEW' END,source_evidence=CASE WHEN discovery_candidates.source_provider='WEB_SEARCH_VERIFIED_V6' THEN discovery_candidates.source_evidence ELSE excluded.source_evidence END,enrichment_status='COMPLETED',enrichment_source_urls=excluded.enrichment_source_urls,enriched_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),`web:${domain}`,h.name,type,state,h.city,h.website,h.email||null,h.phone||null,h.instagram||null,h.facebook||null,h.linkedin||null,h.contactName||null,h.contactTitle||null,h.contactUrl,h.score,grade(h.score),h.website,h.evidence,JSON.stringify({title:h.title,snippet:h.snippet,query:h.query,city:h.city,score:h.score}),JSON.stringify(h.sourceUrls)).run();saved++}return saved}

export const onRequestPost:PagesFunction<Env>=async({request,env})=>{if(!env.MINGEAGLE_DB)return Response.json({ok:false,error:'Database is not configured.'},{status:503});const db=env.MINGEAGLE_DB;await ensureTables(db);let jobId='';try{const input=await request.json() as Input;const state=clean(input.stateCode,2).toUpperCase(),type=clean(input.customerType,80).toUpperCase(),target=Math.min(30,Math.max(5,Math.round(Number(input.targetCount||20))));if(!allowedState.test(state))return Response.json({ok:false,error:'请选择有效的美国州。'},{status:400});if(!allowedTypes.has(type))return Response.json({ok:false,error:'不支持的客户类型。'},{status:400});jobId=crypto.randomUUID();await db.prepare(`INSERT INTO discovery_jobs (id,state_region,customer_type,target_count,source_provider) VALUES (?,?,?,?,'WEB_EXPANSION_V1')`).bind(jobId,state,type,target).run();const cities=(METROS[state]||FALLBACK).slice(0,8),terms=TERMS[type]||TERMS.BASKETBALL_TRAINING;const plans:Array<{city:string;q:string}>=[];for(let i=0;i<cities.length;i++){plans.push({city:cities[i],q:`${terms[i%terms.length]} ${STATE_NAMES[state]||state}`});if(i<5)plans.push({city:cities[i],q:`${terms[(i+2)%terms.length]} ${STATE_NAMES[state]||state}`})}const searches=await Promise.allSettled(plans.slice(0,13).map(p=>bing(p.q,p.city)));const raw=searches.flatMap(r=>r.status==='fulfilled'?r.value:[]),byDomain=new Map<string,Hit>();for(const h of raw){const d=domainOf(h.url);if(!d)continue;const old=byDomain.get(d);if(!old||preScore(h,type)>preScore(old,type))byDomain.set(d,h)}const candidates=[...byDomain.values()].sort((a,b)=>preScore(b,type)-preScore(a,type)).slice(0,14);const checked=candidates.length;const verified:Verified[]=[];for(let i=0;i<candidates.length;i+=4){const batch=candidates.slice(i,i+4);const rs=await Promise.allSettled(batch.map(h=>verify(h,type,state)));verified.push(...rs.flatMap(r=>r.status==='fulfilled'&&r.value?[r.value]:[]));if(verified.length>=Math.min(8,target))break}const found=await save(db,verified,state,type,Math.min(10,target));await db.prepare(`UPDATE discovery_jobs SET status='COMPLETED',result_count=?,completed_at=CURRENT_TIMESTAMP WHERE id=?`).bind(found,jobId).run();return Response.json({ok:true,found,checked,verified:verified.length,mode:'WEB_EXPANSION_V1',provider:'WEB_EXPANSION_V1',note:found?`Web扩展源新增或更新 ${found} 个通过业务与地区双重验证的机构。`:`Web扩展源检查 ${checked} 个高潜官网，本次未新增通过验证的机构。`})}catch(error){const msg=error instanceof Error?error.message:'Web expansion failed.';if(jobId)await db.prepare(`UPDATE discovery_jobs SET status='FAILED',error=?,completed_at=CURRENT_TIMESTAMP WHERE id=?`).bind(msg.slice(0,1000),jobId).run();return Response.json({ok:false,error:msg},{status:502})}};