import { publicPhone, publicPhones, organizationName } from '../../../lib/public-contacts';
interface Env { MINGEAGLE_DB: D1Database }

type Row = Record<string, unknown>;
type Input = { candidateId?: string };
type PageResult = { url:string; html:string };

const clean=(v:unknown,max=1000)=>typeof v==='string'?v.trim().slice(0,max):'';

async function ensureColumns(db:D1Database){
  const info=await db.prepare(`PRAGMA table_info(discovery_candidates)`).all<{name:string}>();const names=new Set(info.results.map(r=>r.name));
  const columns:Array<[string,string]>=[['linkedin_url','TEXT'],['contact_person_name','TEXT'],['contact_person_title','TEXT'],['website_contact_url','TEXT'],['enrichment_status',`TEXT NOT NULL DEFAULT 'NOT_STARTED'`],['enrichment_source_urls','TEXT'],['enrichment_error','TEXT'],['enriched_at','TEXT']];
  for(const [name,definition] of columns){if(names.has(name))continue;try{await db.prepare(`ALTER TABLE discovery_candidates ADD COLUMN ${name} ${definition}`).run()}catch{}}
}
function privateIpv4(host:string){const p=host.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return false;return p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||p[0]===0}
function safeUrl(value:string,base?:string){let u:URL;try{u=new URL(value,base)}catch{throw new Error('Website URL is invalid.')}if(!['http:','https:'].includes(u.protocol))throw new Error('Only public HTTP/HTTPS websites are supported.');const h=u.hostname.toLowerCase().replace(/\.$/,'');if(!h||h==='localhost'||h.endsWith('.local')||h.endsWith('.internal')||privateIpv4(h)||h==='::1'||h.startsWith('fc')||h.startsWith('fd')||h.startsWith('fe80:'))throw new Error('Private/local website addresses are not allowed.');if(u.port&&!['80','443'].includes(u.port))throw new Error('Non-standard website ports are not allowed.');u.hash='';return u}
async function fetchHtml(input:string,base?:string):Promise<PageResult>{let current=safeUrl(input,base);for(let i=0;i<4;i++){const c=new AbortController();const t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(current.toString(),{redirect:'manual',headers:{accept:'text/html,application/xhtml+xml;q=0.9,*/*;q=0.1','user-agent':'MING-EAGLE-Public-Website-Enrichment/2.0 (+https://www.mingeagle.com)'},signal:c.signal});if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');if(!loc)throw new Error('Website redirect has no location.');current=safeUrl(loc,current.toString());continue}if(!r.ok)throw new Error(`Website returned HTTP ${r.status}.`);const ct=r.headers.get('content-type')||'';if(!/text\/html|application\/xhtml/i.test(ct))throw new Error('Website did not return HTML.');return {url:current.toString(),html:(await r.text()).slice(0,900000)}}finally{clearTimeout(t)}}throw new Error('Website redirected too many times.')}
function decode(v:string){return v.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function textOf(html:string){return decode(html).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function linksOf(html:string,base:string){const out:string[]=[];const re=/href\s*=\s*["']([^"']+)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){const raw=decode(m[1]).trim();if(!raw||raw.startsWith('#')||/^(javascript|data):/i.test(raw))continue;try{out.push(new URL(raw,base).toString())}catch{}}return Array.from(new Set(out))}
function validEmail(v:string){const e=v.toLowerCase().replace(/^mailto:/,'').split('?')[0].trim();if(!/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9.-]+\.[a-z]{2,}$/i.test(e))return '';if(/\.(png|jpg|jpeg|gif|webp|svg|css|js)$/i.test(e)||/^(example|test|name)@/i.test(e))return '';return e.slice(0,320)}
function emailsOf(html:string){const d=decode(html);const set=new Set<string>();for(const m of d.matchAll(/mailto:([^"'<>\s?]+)/gi)){const e=validEmail(m[1]);if(e)set.add(e)}for(const raw of d.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]){const e=validEmail(raw);if(e)set.add(e)}return [...set]}
const phonesOf=publicPhones;
function firstSocial(links:string[],domains:string[]){return links.find(link=>{try{const h=new URL(link).hostname.toLowerCase();return domains.some(d=>h===d||h.endsWith(`.${d}`))}catch{return false}})||''}
function whatsappOf(links:string[]){const link=firstSocial(links,['wa.me','whatsapp.com']);if(!link)return '';try{const u=new URL(link);return u.hostname==='wa.me'?u.pathname.replace(/\D/g,'').slice(0,20)||link:u.searchParams.get('phone')?.replace(/\D/g,'').slice(0,20)||link}catch{return link}}
function chooseEmail(emails:string[],host:string){const domain=host.toLowerCase().replace(/^www\./,'');return emails.find(e=>e.endsWith(`@${domain}`))||emails.find(e=>/^(sales|info|contact|hello|office|admin|coach|training|orders)@/i.test(e))||emails[0]||''}

const BAD_NAME_WORDS=new Set(['at','the','new','our','your','basketball','academy','training','program','programs','team','teams','contact','about','director','coach','manager','owner','founder','staff','membership','sports','adult','youth']);
function validPersonName(value:string){const v=clean(value,120).replace(/\s+/g,' ');const parts=v.split(' ');if(parts.length<2||parts.length>3)return false;if(parts.some(p=>BAD_NAME_WORDS.has(p.toLowerCase())))return false;return parts.every(p=>/^[A-Z][A-Za-z'’-]{1,30}$/.test(p))}
function extractPerson(text:string){
  const roles='Owner|Founder|Co-Founder|Executive Director|Program Director|Basketball Director|Training Director|Head Coach|General Manager|Operations Director|Athletic Director|Director of Athletics|PE Teacher|Physical Education Teacher|Physical Education Director|Sports Coordinator|Athletic Coordinator|Activities Director|Recreation Director|Purchasing Manager|Procurement Manager|Procurement Officer|Purchasing Director|Buyer|Operations Manager|School Administrator|Business Manager|Principal|Vice Principal|Head of School|Director|Coach|Manager|President|CEO';
  const name="([A-Z][A-Za-z'’-]{1,30}(?:\\s+[A-Z][A-Za-z'’-]{1,30}){1,2})";
  const patterns=[new RegExp(`${name}\\s*(?:[-–—|,:]|\\bis\\s+(?:the\\s+)?)\\s*(${roles})`),new RegExp(`(${roles})\\s*(?:[-–—|,:])?\\s*${name}`)];
  for(let i=0;i<patterns.length;i++){const m=text.match(patterns[i]);if(!m)continue;const person=i===0?m[1]:m[2];const title=i===0?m[2]:m[1];if(validPersonName(person))return {name:clean(person,120),title:clean(title,120)}}return {name:'',title:''}
}
function genericOrgName(value:string){const v=clean(value,120);return !v||/^(home|basketball|adult basketball|youth basketball|basketball training|basketball academy|training|academy|programs?|sports|athletics|contact|about|team|coaches?)$/i.test(v)}
function metaContent(html:string,key:string){const esc=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const p of [new RegExp(`<meta[^>]+(?:property|name)=["']${esc}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${esc}["']`,'i')]){const m=html.match(p);if(m)return textOf(m[1])}return ''}
function titleOf(html:string){const m=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?textOf(m[1]):''}
function orgName(html:string,url:string,current:string){const candidates=[metaContent(html,'og:site_name'),metaContent(html,'application-name')];for(const t of [titleOf(html),current]){for(const p of t.split(/\s+[|–—:]\s+|\s+-\s+/).reverse())candidates.push(clean(p,120))}for(const c of candidates){if(!genericOrgName(c)&&c.length<=100)return c}try{return new URL(url).hostname.replace(/^www\./,'').split('.')[0].replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).slice(0,100)}catch{return current}}
function grade(score:number){return score>=80?'A':score>=60?'B':'C'}

export const onRequestPost:PagesFunction<Env>=async({request,env})=>{
  if(!env.MINGEAGLE_DB)return Response.json({ok:false,error:'Database is not configured.'},{status:503});const db=env.MINGEAGLE_DB;await ensureColumns(db);
  const input=await request.json() as Input;const candidateId=clean(input.candidateId,120);if(!candidateId)return Response.json({ok:false,error:'candidateId is required.'},{status:400});
  const row=await db.prepare(`SELECT * FROM discovery_candidates WHERE id=? LIMIT 1`).bind(candidateId).first<Row>();if(!row)return Response.json({ok:false,error:'Candidate not found.'},{status:404});const website=clean(row.website,1000);if(!website)return Response.json({ok:false,error:'This candidate has no public website to inspect.'},{status:400});
  await db.prepare(`UPDATE discovery_candidates SET enrichment_status='RUNNING',enrichment_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(candidateId).run();
  try{
    const home=await fetchHtml(website);const homeUrl=new URL(home.url);const pages:PageResult[]=[home];const same=linksOf(home.html,home.url).filter(link=>{try{return new URL(link).hostname.toLowerCase().replace(/^www\./,'')===homeUrl.hostname.toLowerCase().replace(/^www\./,'')}catch{return false}});const preferred=same.filter(link=>/\/(contact|contact-us|about|about-us|team|staff|directory|coaches|coach|leadership|our-team|athletics|athletic|physical-education|pe|purchasing|procurement|vendors?|business-office|administration)(?:[/?#]|$)/i.test(link));for(const target of Array.from(new Set(preferred)).slice(0,2)){try{pages.push(await fetchHtml(target))}catch{}}
    const combinedHtml=pages.map(p=>p.html).join('\n');const combinedText=pages.map(p=>textOf(p.html)).join(' ');const links=pages.flatMap(p=>linksOf(p.html,p.url));const email=chooseEmail(emailsOf(combinedHtml),homeUrl.hostname);const phone=phonesOf(combinedHtml,combinedText)[0]||'';const whatsapp=whatsappOf(links);const instagram=firstSocial(links,['instagram.com']);const facebook=firstSocial(links,['facebook.com','fb.com']);const linkedin=firstSocial(links,['linkedin.com']);const person=extractPerson(combinedText);const sourceUrls=pages.map(p=>p.url);const contactUrl=pages.find(p=>/contact/i.test(p.url))?.url||pages[1]?.url||home.url;const improvedName=organizationName(orgName(home.html,home.url,clean(row.name,160)));
    const mergedEmail=clean(row.email,320)||email;const mergedPhone=publicPhone(clean(row.phone,160))||phone;const mergedWhatsapp=clean(row.whatsapp,320)||whatsapp;const mergedInstagram=clean(row.instagram_url,1000)||instagram;const mergedFacebook=clean(row.facebook_url,1000)||facebook;const mergedLinkedin=clean(row.linkedin_url,1000)||linkedin;const oldPerson=clean(row.contact_person_name,120);const finalPerson=person.name||(validPersonName(oldPerson)?oldPerson:'');const finalTitle=person.title||(finalPerson?clean(row.contact_person_title,120):'');let score=Math.max(0,Number(row.lead_score||0));if(email&&!clean(row.email,320))score+=10;if(phone&&!clean(row.phone,160))score+=6;if(finalPerson&&finalTitle)score+=5;if(linkedin)score+=3;if(instagram||facebook)score+=2;score=Math.min(100,Math.round(score));if(!mergedEmail&&!mergedPhone&&!mergedWhatsapp)score=Math.min(79,score);
    await db.prepare(`UPDATE discovery_candidates SET name=?,website=?,email=?,phone=?,whatsapp=?,instagram_url=?,facebook_url=?,linkedin_url=?,contact_person_name=?,contact_person_title=?,website_contact_url=?,lead_score=?,grade=?,enrichment_status='COMPLETED',enrichment_source_urls=?,enrichment_error=NULL,enriched_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(improvedName,home.url,mergedEmail||null,mergedPhone||null,mergedWhatsapp||null,mergedInstagram||null,mergedFacebook||null,mergedLinkedin||null,finalPerson||null,finalTitle||null,contactUrl,score,grade(score),JSON.stringify(sourceUrls),candidateId).run();
    let synced=false;if(clean(row.crm_lead_id,120)){try{const r=await fetch(new URL('/api/admin/discovery-enrich',request.url).toString(),{method:'POST',headers:{'content-type':'application/json','x-admin-key':request.headers.get('x-admin-key')||''},body:JSON.stringify({action:'SYNC_CRM',candidateId})});synced=r.ok}catch{}}
    return Response.json({ok:true,candidateId,pagesChecked:sourceUrls.length,found:{email:Boolean(email),phone:Boolean(phone),whatsapp:Boolean(whatsapp),instagram:Boolean(instagram),facebook:Boolean(facebook),linkedin:Boolean(linkedin),contactPerson:Boolean(finalPerson),organizationName:improvedName!==clean(row.name,160)},score,grade:grade(score),synced});
  }catch(error){const msg=error instanceof Error?error.message:'Website enrichment failed.';await db.prepare(`UPDATE discovery_candidates SET enrichment_status='FAILED',enrichment_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(msg.slice(0,1000),candidateId).run();return Response.json({ok:false,error:msg},{status:500})}
};
